# Logo
favicon = "images/favicon.png"
logo_desktop = "images/logo.png"
logo_desktop_width = "350px"
logo_mobile = "images/logo-mobile.png"
logo_mobile_width = "100px"

# meta description
author = "Themefisher"
description = "Documentation for the installation and configuration of our themes."
topic_title = "Theme Documentations"
premium_badge = true
edit_page_url = "https://github.com/gethugothemes/documentation/edit/master/content/"
copyright = "Copyright &copy; 2020 [Gethugothemes](https://gethugothemes.com/) Docs build with [Godocs Theme](https://gethugothemes.com/products/godocs-hugo-documentation-theme/)"

# custom script
custom_script= "<script>!function(e,t,n){function a(){var e=t.getElementsByTagName('script')[0],n=t.createElement('script');n.type='text/javascript',n.async=!0,n.src='https://beacon-v2.helpscout.net',e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],'complete'===t.readyState)return a();e.attachEvent?e.attachEvent('onload',a):e.addEventListener('load',a,!1)}(window,document,window.Beacon||function(){}),window.Beacon('init','8f0313a1-19b9-4fb1-b400-01821b9798af');</script>"

[banner]
image = "images/banner.jpg"
subtitle = "We are the biggest hugo theme provider in the market , We will cover all our themes installation documentation here . "
title = "Welcome to Gethugothemes"

[call_to_action]
enable = true
title = "Could not find what you were looking for?"
content = "Feel free to contact us any time to submit your questions or suggestions. You will receive priority support if you are using our premium products."
image = "images/cta-illustration.jpg"
[call_to_action.button]
enable = true
label = "Start a conversation now!"

[navigation_button_bordered]
enable = true
label = "submit ticket"

[navigation_button_solid]
enable = true
label = "guide"
link = "guide"

# plugins loop
[[plugins.js]]
link = "js/plugins/jQuery/jquery.min.js"
[[plugins.js]]
link = "js/plugins/bootstrap/bootstrap.min.js"
[[plugins.js]]
link = "js/plugins/masonry/masonry.min.js"
[[plugins.js]]
link = "js/plugins/featherlight/featherlight.min.js"
[[plugins.js]]
link = "js/plugins/clipboard/clipboard.min.js"
[[plugins.js]]
link = "js/plugins/search/auto-complete.js"
[[plugins.js]]
link = "js/plugins/scrollmenu/scrollmenu.min.js"
[[plugins.js]]
link = "js/plugins/search/search.js"
[[plugins.js]]
link = "js/plugins/search/lunr.min.js"
[[plugins.js]]
link = "js/plugins/search/fuse.min.js"
[[plugins.js]]
link = "js/plugins/search/mark.js"
[[plugins.js]]
link = "js/plugins/search/search-page.js"
[[plugins.js]]
link = "js/plugins/turbolinks/turbolinks.js"